apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: test-compose-broker
spec:
  url: http://bsb-os.apps.eu01.cf.canopy-cloud.com
  # put the basic auth for the broker in a secret, and reference the secret here.
  # service-catalog will use the contents of the secret. The secret should have "username"
  # and "password" keys
  authInfo:
    basicAuthSecret:
      namespace: service-catalog
      name: broker-secret
